# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_organiseprograms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiseprograms',
            name='program',
        ),
        migrations.RemoveField(
            model_name='organiseprograms',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrganisePrograms',
        ),
    ]
