# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_organiseprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='certificates.Certificate')),
            ],
        ),
        migrations.RenameModel(
            old_name='OrganisePrograms',
            new_name='OrganiseProgram',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='organiseprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.Program'),
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
