# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20170525_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiseprogram',
            name='days_attended',
        ),
        migrations.RemoveField(
            model_name='organiseprogram',
            name='qrCode',
        ),
    ]
