# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20170526_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiseprogram',
            name='user',
        ),
    ]
