# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_remove_organiseprogram_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organiseprogram',
            old_name='user1',
            new_name='user',
        ),
    ]
