# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_auto_20170526_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='OrganiseProgram',
            new_name='OrganisedEvent',
        ),
        migrations.RenameField(
            model_name='usercertificateinfo',
            old_name='qrCode',
            new_name='qrcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
