# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_auto_20170527_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercertificateinfo',
            old_name='organise_program',
            new_name='organise_event',
        ),
    ]
