# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_auto_20170527_0958'),
        ('certificates', '0014_auto_20170527_1247'),
    ]

    operations = [
    ]
