# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0019_auto_20170529_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='a'),
        ),
    ]
