# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0022_auto_20170531_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisedevent',
            name='organiser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisedevent',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercertificateinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
