# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0024_auto_20170531_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisedevent',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
