# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0025_auto_20170531_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='logo',
        ),
    ]
