# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0026_remove_certificate_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='certificate',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='certificates.Certificate'),
        ),
    ]
