# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0027_auto_20170602_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisedevent',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
