# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0028_auto_20170603_0608'),
        ('certificates', '0028_auto_20170602_1215'),
    ]

    operations = [
    ]
