# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0029_merge_20170609_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisedevent',
            old_name='event',
            new_name='organised_event',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='usercertificateinfo',
            old_name='organise_event',
            new_name='organised_event',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='name',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='usercertificateinfo',
            name='days_attended',
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usercertificateinfo',
            name='user_type',
            field=models.ManyToManyField(related_name='type_user', to='certificates.UserType'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='certificates.Certificate'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
