# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0030_auto_20170603_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificateinfo',
            name='days_attended',
        ),
        migrations.AddField(
            model_name='usercertificateinfo',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
