# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0030_auto_20170607_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='user_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
        migrations.AlterField(
            model_name='usercertificateinfo',
            name='user_type',
            field=models.ManyToManyField(related_name='type_of_user', to='certificates.UserType'),
        ),
    ]
