# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0030_auto_20170609_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificateinfo',
            name='user_type',
        ),
    ]
