# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0032_auto_20170609_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificateinfo',
            name='user_type',
        ),
    ]
