# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0032_auto_20170606_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercertificateinfo',
            old_name='organise_event',
            new_name='organised_event',
        ),
        migrations.AddField(
            model_name='usercertificateinfo',
            name='user_type',
            field=models.ManyToManyField(related_name='user_type', to='certificates.UserType'),
        ),
    ]
