# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0036_auto_20170609_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificateinfo',
            name='user_type',
            field=models.ManyToManyField(related_name='user_type', to='certificates.UserType'),
        ),
    ]
