# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0037_auto_20170612_0506'),
        ('certificates', '0037_auto_20170609_1435'),
    ]

    operations = [
    ]
