# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0038_merge_20170613_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
