# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0039_auto_20170613_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
