# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0041_auto_20170613_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificates.Certificate'),
        ),
    ]
