# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0043_auto_20170615_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
