# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0044_auto_20170616_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisedevent',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
