# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0045_auto_20170619_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisedevent',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
