# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0046_auto_20170621_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisedevent',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='organisedevent',
            name='start_date',
            field=models.DateField(),
        ),
    ]
